[package]
org= "ballerinax"
name= "microsoft.onedrive"
version= "2.0.0"
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Freemium", "Vendor/Microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive"
license = ["Apache-2.0"]

[build-options]
observability-included=true
