[package]
distribution = "2201.2.0"
org= "ballerinax"
name= "microsoft.onedrive"
version= "2.3.0"
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Freemium", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive"
license = ["Apache-2.0"]

[build-options]
observability-included=true
